# tomlファイル用シンタックスハイライト
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'keith/swift.vim'
on_ft = ['swift']

[[plugins]]
repo = 'alvan/vim-closetag'
hook_add='''
let g:closetag_filenames = '*.html,*.vue,*.xml'
'''
on_ft = ['html', 'vue', 'xml']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'vue', 'js', 'xml', 'css']
